services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
      - "3306:${DB_PORT}"  
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      timeout: 1s
      retries: 20
    networks:
      - network

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   env_file: .env
  #   environment: 
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
  #     - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
  #     - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
  #   volumes:
  #     - ${PWD}/_data/mongo:/data/db
  #     - ${PWD}/docker/_mongo/fixtures:/import
  #     - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - network

  redis:
    image: 'redis:alpine'
    hostname: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
