services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/
    ports:
      - '8080:8000'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker_volume/mysql_data:/var/lib/mysql
    ports:
      - '3306:${DB_PORT}'
    healthcheck:
      test:
        [
          'CMD',
          'mysql',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${DB_PASSWORD}',
          '-e',
          'SELECT 1',
        ]
      timeout: 1s
      retries: 20
    networks:
      - network

  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - ./docker_volume/mongodb_data:/var/lib/mongodb
    ports:
      - 27017:27017
    networks:
      - network

  redis:
    image: 'redis:alpine'
    restart: always
    hostname: redis
    ports:
      - '6379:${REDIS_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ./docker_volume/redis-data:/var/lib/redis
    networks:
      - network

volumes:
  mysql_data:
  redis-data:

networks:
  network:
